

default:
	@pyschism bctides hgrid.ll -o outputs --iettype-3 \
	 --ifltype-3 --tidal-database=tpxo --major-constituents \
     --start-date=2018-07-24T00:00:00 --run-days=36 --overwrite \
	 --log-level=info